### ISSUE TITLE
How do I modify the health check interval of aws NLB TargetGroup

### ISSUE THREAD

**Issue by 3Golds** [kubernetes/legacy-cloud-providers#2]
I created a service (type=loadBalancer, service.beta.kubernetes.io/aws-load-balancer-type: nlb), but I found that can't change HealthCheckIntervalSeconds.

```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    # Enable PROXY protocol
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    # by default the type is elb (classic load balancer).
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  # this setting is to make sure the source IP address is preserved.
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
```

I found through [aws_loadbalancer.go](https://github.com/kubernetes/legacy-cloud-providers/blob/master/aws/aws_loadbalancer.go#L5381) that it was set to 30s, but I didn't find anything that could be changed.

Excuse me, when I am in Kubernetes through service to create change HealthCheckIntervalSeconds NLB does not support?
